
[background-color="#01303a"]
== Creating a Gradle Kotlin DSL build

=== Creating a Gradle Kotlin DSL build

* With Gradle locally installed
* `gradle init`

ASCIINEMA DEMO HERE

=== Creating a Gradle Kotlin DSL build

* From a Web UI
* https://gradle-initializr.cleverapps.io/

[source,text]
----
➜ mkdir webinar-app \
    && cd webinar-app \
    && curl https://gradle-initializr.cleverapps.io/starter.zip \
    -d type=kotlin-application \
    -d dsl=kotlin \
    -d projectName=webinar-app \
    -d gradleVersion=5.3.1 \
    -o webinar-app.zip \
    && unzip -o webinar-app.zip \
    && rm webinar-app.zip
----

WEBSITE & CURL CAST DEMO HERE

=== Anatomy of the build

[source,text]
----
.
├── settings.gradle.kts
├── build.gradle.kts
├── gradlew
├── gradlew.bat
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
└── src
    ├── main
    │   └── kotlin
    │       └── *
    └── test
        └── kotlin
            └── *
----

[.notes]
--
* .kts script file extension
--

[transition=none]
=== Anatomy of the build

[source,text]
----
.
├── settings.gradle.kts                 <=
├── build.gradle.kts
├── gradlew
├── gradlew.bat
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
└── src
    ├── main
    │   └── kotlin
    │       └── *
    └── test
        └── kotlin
            └── *
----


[transition=none]
=== `settings.gradle.kts`

[source,kotlin]
----
rootProject.name = "webinar-app"
----

[.notes]
--
* settings for the whole build
* its project structure
* other global build configurations such as build cache, where to find plugins, etc
--

[transition=none]
=== Anatomy of the build

[source,text]
----
.
├── settings.gradle.kts
├── build.gradle.kts                    <=
├── gradlew
├── gradlew.bat
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
└── src
    ├── main
    │   └── kotlin
    │       └── *
    └── test
        └── kotlin
            └── *
----

[transition=none]
=== `build.gradle.kts`

[source,kotlin]
----
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.3.21"
    application
}
repositories {
    jcenter()
}
dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}
application {
    mainClassName = "webinar.app.AppKt"
}
----

[.notes]
--
* the root project build script
* configures a Kotlin JVM application
* sets up the repository where to find the dependencies
* sets up the dependencies, if you want to know more about this important topic see the Dependency Management Fundamentals webinar
* sets up the application entry point
--

[transition=none]
=== Anatomy of the build

[source,text]
----
.
├── settings.gradle.kts
├── build.gradle.kts
├── gradlew                             <=
├── gradlew.bat                         <=
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar          <=
│       └── gradle-wrapper.properties   <=
└── src
    ├── main
    │   └── kotlin
    │       └── *
    └── test
        └── kotlin
            └── *
----

[.notes]
--
* the Gradle wrapper is a way for a build to declare/specify the version of Gradle it uses
* the script will automatically download the declared Gradle distribution
* makes it easy to get the build up and running (either in CI or some other developer's machine)
* only requires a JVM to bootstrap the whole build
--

[transition=none]
=== Anatomy of the build

[source,text]
----
.
├── settings.gradle.kts
├── build.gradle.kts
├── gradlew
├── gradlew.bat
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
└── src
    ├── main
    │   └── kotlin
    │       └── *                       <=
    └── test
        └── kotlin
            └── *                       <=
----

[.notes]
--
* and the source code for the application and tests in the standard layout
--

=== Using the build

[source,text]
----
➜ ./gradlew run

> Task :run
Hello world.

BUILD SUCCESSFUL in 0s
2 actionable tasks: 2 executed
----

<demo here>

[.notes]
--
* and here we just use the Gradle wrapper to execute the `run` task provided by the `application` plugin
--

