[background-color="#01303a"]
== Customizing the build

=== `build.gradle.kts`

[source,kotlin]
----
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.3.21"
    application
}
repositories {
    jcenter()
}
dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}
application {
    mainClassName = "webinar.app.AppKt"
}
----

[.notes]
--
* now say we want to change the way our application runs
* for example, by limiting the amount of memory to only 4MB
* with the JVM we can achieve that by using the `-Xmx` command line argument
* we should be able to tell the `application` plugin to do just that
* so let's take a closer look at our build script and its `application` block
* >> transitions to IDE here with the script already open
* that's what's called an extension configuration block
* in general, extensions are how plugins extend the Gradle DSL
* in our build, the application plugin is extending the Gradle DSL with the application extension
* let's have a look at the configuration options we have
** CTRL+SPACE on application block, show docs
* let's set the jvm args to a listOf("-Xmx4m")
--

=== Configuring the `application` plugin

[source,kotlin]
----
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.3.21"
    application
}
repositories {
    jcenter()
}
dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}
application {
    mainClassName = "webinar.app.AppKt"
    applicationDefaultJvmArgs = listOf("-Xmx4m")
}
----

[.notes]
--
* with our plugin now configured we can run some tasks and see its effect
--

=== Running the app with the new arguments

* demo with ./gradlew run -i
** highligh the new `-Xmx4m` argument
* demo ./gradlew install
** open script and highlight new argument

=== Configuring the Kotlin compiler

[source,kotlin]
----
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.3.21"
    application
}
repositories {
    jcenter()
}
dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}
application {
    mainClassName = "webinar.app.AppKt"
    applicationDefaultJvmArgs = listOf("-Xmx4m")
}
----

[.notes]
--
* now, say we want to make sure we never introduce compilation warnings into our code base
* we can achieve that by configuring the task that runs the Kotlin compiler
* >> back to the IDE
** >> add tasks block
** >> type `compile` wait for popup
** >> select `compileKotlin {}`
** at this point there should be a way to configure the compiler options
** >> type `options` wait for popup
** >> select `kotlinOptions {}`
** we want to configure how warnings are handled
** >> type `warn` wait for popup
** >> select `allWarningsAsErrors`
** >> check the docs (^J)
** >> assign true
** That should be enough
--

=== Building with the new configuration

[source,kotlin]
----
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.3.21"
    application
}
repositories {
    jcenter()
}
dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}
application {
    mainClassName = "webinar.app.AppKt"
    applicationDefaultJvmArgs = listOf("-Xmx4m")
}
tasks {
    compileKotlin {
        kotlinOptions { allWarningsAsErrors = true }
    }
}
----

[.notes]
--
* demo introducing warning by duplicating `return "Hello world"` line
** >> navigate to App
** >> duplicate line
** >> run anything `gradle run`
** >> highlight warning output
** >> fix the code
** >> run again
--

=== What we learned so far

* we can change the behavior of the build by
** configuring extensions and tasks
** both contributed by plugins
** in other words, plugins extend the Gradle DSL which can then be configured in scripts like the one we just saw

=== Going further: modularizing

*DEMO*

[.notes]
--
* split the build into core and app
** `apply false` in the root project to control the version of the plugin in a single place
**  duplicate `compileKotlin` configuration logic
* dedupe the logic by moving the duplicated compileTask configuration into the root build
** cross `subprojects` configuration with `val compileKotlin by ...`
--

=== What we learned - modularizing

[%step]
* project evaluation order follows the hierarchy
* script classpath is inherited
* cross-configuration requires dynamic references
* type-safe accessors are not always available
* see the _Kotlin DSL Primer_ in the User Manual for more information


=== Going further: interoperability

*Using non statically typed APIs and DSLs from a statically typed language*

*DEMO*

[.notes]
--
* introduce company wide Groovy script that validates license headers
** Groovy script provides extension to configure license (defaults to LGPL)
** `app` needs to configure script to use GPL
** `licensing` extension will be untyped because Groovy script type
** use `withGroovyBuilder` to set the license (an enum that can be `setProperty("license", "GPL")` from `app`
--


=== What we learned - interoperability

[%step]
* you can mix Kotlin and Groovy scripts
* when types are not available, `withGroovyBuilder {}` to the rescue
* see the _Kotlin DSL Primer_ in the User Manual for more information
