[background-color="#01303a"]
== Organizing build logic

===  Patterns for organizing build logic

* cross-configuration
* buildSrc
* sharing build logic between builds

[.notes]
--
* build script logic can get unwieldy with conventions for Kotlin, Java, Scala, Groovy
* sharing the plugin with a wider audience
--

=== Organizing build logic with `buildSrc`

[source,text]
----
.
├── buildSrc
│   ├── build.gradle.kts
│   ├── settings.gradle.kts
│   └── src
│       └── *
├── app
│   ├── build.gradle.kts
│   └── src
│       └── *
├── core
│   ├── build.gradle.kts
│   └── src
│       └── *
├── gradle
│   └── *
├── gradlew.bat
├── gradlew
├── build.gradle.kts
└── settings.gradle.kts
----

[.notes]
--
** extract convention plugin into `buildSrc/src/main/kotlin/kotlin-conventions.gradle.kts`
*** setup `buildSrc` with `kotlin-dsl` plugin
*** move `kotlin("jvm")` plugin dependency to `buildSrc` / `dependencies`
*** create `src/main/kotlin/kotlin-conventions.gradle.kts`
*** plugins block with `kotlin("jvm")` plugin
*** move `compileKotlin` configuration into `kotlin-conventions`
*** simplify script plugin with type-safe accessor
*** `subprojects { apply(plugin = "kotlin-conventions") }` in root
*** demonstrate introducing warning and failing the build still works
* quick demo testing buildSrc
--

=== What we learned

[%step]
* `buildSrc` is the conventional build for build logic
* the `kotlin-dsl` plugin brings the Gradle Kotlin DSL support to Kotlin source sets
* Gradle Kotlin DSL scripts in Kotlin source sets are exposed as Gradle plugins
* see the _Kotlin DSL Primer_ in the User Manual for more information


=== Sharing build logic between builds

[source,text]
----
.
├── build-logic
│   ├── build.gradle.kts
│   ├── settings.gradle.kts
│   └── src
│       └── *
└── webinar-app
    ├── app
    │   ├── build.gradle.kts
    │   └── src
    │       └── *
    ├── core
    │   ├── build.gradle.kts
    │   └── src
    │       └── *
    ├── gradle
    │   └── *
    ├── gradlew
    ├── gradlew.bat
    ├── build.gradle.kts
    └── settings.gradle.kts
----
[.notes]
--
* extract plugin to separate build
* freeze the project name in settings.gradle.kts
* add group and version to `build.gradle.kts`
* to consume the plugin
** include build
** set up `gradle.rootProject.buildscript` classpath (dependencies and repositories)
--

